pipeline {
    agent any

    environment {
        // Set up a virtualenv directory
        VENV_DIR = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from GitHub
                git credentialsId: 'brianmaleek', url: 'https://github.com/brianmaleek/alx-backend-python/tree/main/messaging_app.git'
            }
        }
        stage('Set up Python & Install Dependencies') {
            steps {
                // Use ShiningPanda to create a virtualenv and install requirements
                sh '''
                    python3 -m venv ${VENV_DIR}
                    . ${VENV_DIR}/bin/activate
                    pip install --upgrade pip
                    pip install -r messaging_app/requirements.txt
                '''
            }
        }
        stage('Run Tests') {
            steps {
                // Run pytest and generate a JUnit XML report
                sh '''
                    . ${VENV_DIR}/bin/activate
                    pytest messaging_app/tests --junitxml=report.xml
                '''
            }
            post {
                always {
                    // Archive the test report
                    junit 'report.xml'
                }
            }
        }
    }
    options {
        // Allow manual trigger only
        disableConcurrentBuilds()
    }
}
